<header class="w-full container mx-auto">
    <div class="flex flex-col items-center py-12">
        <a href="/" class="font-bold text-gray-800 uppercase text-center hover:text-gray-700 text-5xl tsukimi">
            Code Chronicles
        </a>
        <p class="text-center max-w-2xl text-lg text-gray-600 mt-3">
            {{-- {{ \App\Models\TextWidget::getWidget('subheader', 'title') }} --}}
            Articles about PHP, Laravel, Livewire, Tailwind, AlpineJs and MySQL 
            generated by <a href="https://openai.com/" target="_blanket" class="text-indigo-600 hover:underline hover:text-indigo-500">OpenAI</a>
        </p>
    </div>
</header>